name: Tsukushi
version: git
summary: OfflineIMAP
description:
  OfflineIMAP is software that downloads your email mailbox(es) as local
  Maildirs. OfflineIMAP will synchronize both sides via IMAP.

confinement: devmode

parts:
  offlineimap:
    plugin: python
    python-version: python3
    source: .

apps:
  offlineimap:
    command: bin/offlineimap
