name: tsukushi
version: "1.0" # just for humans, typically '1.2+git' or '1.3.2'
summary: A code editor created by kivy.
description: |
  Tsukushi is a code editor.
  feature：
  - Syntax highlight for python
  - Project generation

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
  tsukushi:
    source: https://github.com/Eleven-junichi2/tsukushi.git
    source-tag: v1.0
    plugin: python
    python-version: python3
    requirements: 
