name: tsukushi # you probably want to 'snapcraft register <name>'
version: git # just for humans, typically '1.2+git' or '1.3.2'
summary: A code editor created by Kivy. # 79 char long summary
description: |
  Tsukushi is a code editor.
  feature:
  - Syntax highlight for python
  - Project generation

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

apps:
  tsukushi:
    command: bash "$SNAP/wrapper.sh"
    plugs:
      - opengl
      - x11
      - unity7
      - system-observe
      - hidraw
      - locale-control

parts:
  move-src:
    plugin: dump
    source: ./tsukushi
    # source: https://github.com/Eleven-junichi2/tsukushi/releases/download/v1.0/Tsukushi-1.0_x64.tar.xz
    organize:
      snap_wrapper.sh: wrapper.sh
    #   main.py: bin/tsukushi


  kivy:
    plugin: nil
    build-packages:
      - python3
      - python3-kivy
      - libmtdev1
