name: tsukushi # you probably want to 'snapcraft register <name>'
version: git # just for humans, typically '1.2+git' or '1.3.2'
summary: A code editor created by Kivy. # 79 char long summary
description: |
  Tsukushi is a code editor.
  feature:
  - Syntax highlight for python
  - Project generation

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

apps:
  tsukushi:
    command: tsukushi
    # plugs:
    #   - opengl
    #   - x11
    #   - unity7
    #   - system-observe
    #   - hidraw
    #   - locale-control

parts:
  tsukushi:
    source: .
    # source: https://github.com/Eleven-junichi2/tsukushi.git
    source-tag: v1.0.18
    plugin: python
    override-build: |
      curl -O https://www.python.org/ftp/python/3.7.0/Python-3.7.0.tgz
      tar xvfz Python-3.7.0.tgz
      cd Python-3.7.0/
      ./configure --prefix=/usr/local/python370 --with-ensurepip
      make
      sudo make install

